// app/layout.tsx
import "./globals.css";
import { Noto_Sans_JP, Poppins } from "next/font/google";
import type { Metadata } from "next";
import Header from "./components/Header";

// フォント読み込み
const notojp = Noto_Sans_JP({
  subsets: ["latin", "latin-ext", "latin"],
  weight: ["400", "700"],
  variable: "--font-notojp",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Nellzz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${notojp.variable} ${poppins.variable}`}>
      <body className="font-notojp flex flex-col min-h-screen bg-white text-black dark:bg-[#1c1c1c] dark:text-white transition-colors duration-300">
      <Header />
      <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}

